### ISSUE TITLE
Julia Client Internal Error for completion 

### ISSUE THREAD

**Issue by tomaklutfu** [JunoLab/CodeTools.jl#16]
Each time I type something like below

``` julia
    @elapsed x1=GradientDescent.GradientDescentv1(A,b,α,200000)
```

I get annoying pop-up error saying

``` julia
PCRE.exec error: match limit exceeded
  in prefix at ....../Codetools/src/completions.jl:74
  in anonymous ..../Atom/src/completions.jl:8 
```

on Atom 1.7.2, julia 0.4.5, Atom.jl 0.4.2, CodeTools.jl 0.3.0

**Comment by pfitzseb** [comment]
Same as https://github.com/JunoLab/atom-julia-client/issues/112.
Try `Pkg.checkout("CodeTool")` until there's a new version tagged (@MikeInnes, could you do that?).

**Comment by tomaklutfu** [comment]
Thanks, closing then.
