### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [JunoLab/CodeTools.jl#19]
The latest tagged release has a bunch of depwarns but master doesn't. Could you tag a new release please?

**Comment by MikeInnes** [comment]
Does this package have any dependents other than Atom? I'm not against doing a release now, but was planning to do this + Atom.jl together once it's ready.

**Comment by ranjanan** [comment]
Oh it's just Atom. Well in that case, you could do it whenever Atom is ready. Thanks!
