### ISSUE TITLE
Module detection ends early

### ISSUE THREAD

**Issue by jamii** [JunoLab/CodeTools.jl#21]
Eg in [this file](https://gist.github.com/jamii/bad4f9ff2a6b8c4536cfad8f1e6a5a6e) in Atom I get module Main/Graph until line 21 and module Main for the rest of the file. Seems to happen whenever a `begin` is not the first thing on the line.

This used to work fine for me. Maybe related to [this change](https://github.com/JunoLab/CodeTools.jl/commit/ee72912cd4c06d6bf28a15e9b411b65a0b3af9e5)?

**Comment by pfitzseb** [comment]
This should be fixed by https://github.com/JunoLab/CodeTools.jl/commit/a96c29a32318d45cfa407c2eae735795ee7cc333. Would you mind trying that locally and reporting back?

**Comment by jamii** [comment]
Fixes most of them. I think you need to handle `quote` in there too.

**Comment by jamii** [comment]
eg 

``` julia
function project(columns, los, his, next_los, next_his, var, body)
  for (column, lo, hi, next_lo, next_hi) in zip(columns, los, his, next_los, next_his)
    body = quote
      $next_lo, c = gallop($column, $var, $lo, $hi, 0)
      if (c == 0)
        $next_hi, _ = gallop($column, $var, $next_lo+1, $hi, 1)
        $body
      end
    end
  end
  body
end
```

**Comment by pfitzseb** [comment]
Using [Tokenize.jl](https://github.com/KristofferC/Tokenize.jl) seems like a good way to do this:
https://gist.github.com/pfitzseb/f30d024ec95a8991a5b88d93f91917bf
