### ISSUE TITLE
IMMUTABLE is removed. 

### ISSUE THREAD

**Issue by Roger-luo** [JunoLab/CodeTools.jl#31]
This cause error when I was using master branch of `Atom`.

https://github.com/JunoLab/CodeTools.jl/blob/344fe86d88c1f866ba1a83dfba0acf02c3498bb9/src/module.jl#L64

https://github.com/KristofferC/Tokenize.jl/pull/133

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/CodeTools.jl/commit/13787b03f29854b9d21f9462a5ebe1a45dc2aa6f. Thanks for reporting! :)
